version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: new_password  # Changed from '1234' to 'new_password'
      POSTGRES_DB: iot_events
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: new_user
      RABBITMQ_DEFAULT_PASS: new_password
    ports:
      - "5672:5672"
      - "15672:15672"

